apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
  labels:
    app: mysql
spec:
  clusterIP: None  # Creates a headless service for StatefulSet
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
